language: python
python:
  - "3.5"
install: "pip install -r requirements.txt"
before_install:
  - git clone git@github.com:billcloud-me/python-testing-sample.wiki.git wiki
  - pydoc Books.Book > wiki/Book.md
  - cd wiki
  - git config --global user.email "bill.t.ward@billcloud.me"
  - git config --global user.name "billcloud-me"
  - git add Book.md
  - git commit -m "Generating Pydoc"
  - git push origin master
  - cd ..
script: 
  - tox
  - behave
