language: python
python:
  - "3.5"
install: "pip install -r requirements.txt"
before_install:
  - git clone https://github.com/billcloud-me/python-testing-sample.wiki.git wiki
script: 
  - tox
  - behave
